# Built on the developer machine (Windows) and shipped as changed layers to a private registry on the VPS over an ssh tunnel (deploy/ship.ps1).
# Nothing is installed or built on the VPS.

# ---------- builder ----------
FROM node:22-bookworm-slim AS builder
WORKDIR /app
ENV CI=true NEXT_TELEMETRY_DISABLED=1
RUN corepack enable && corepack prepare pnpm@10.22.0 --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN pnpm install --frozen-lockfile
COPY . .
# Build-time only: Next evaluates route modules while collecting page data (e.g. /api/health), and those import
# src/lib/env.ts, which validates the environment. The build context has no .env (.dockerignore) and a hosted
# builder (Render) passes no runtime secrets into `docker build`, so the builder stage gets inert placeholders.
# They exist ONLY in this stage — the runner stage below starts from a fresh image and reads the real values from
# the runtime environment; nothing here is a secret or reaches the shipped image.
ENV NODE_ENV=production \
    DATABASE_URL=postgres://build:build@127.0.0.1:1/build \
    MIGRATION_DATABASE_URL=postgres://build:build@127.0.0.1:1/build \
    SESSION_SECRET=build-time-placeholder-not-a-secret-000000000000 \
    INITIAL_PASSWORD_KEY=0000000000000000000000000000000000000000000000000000000000000000 \
    PUBLIC_ORIGIN=http://localhost:3000
RUN pnpm build

# ---------- runner ----------
FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV TZ=UTC NODE_ENV=production HOSTNAME=0.0.0.0 PORT=3000 NEXT_TELEMETRY_DISABLED=1
ARG APP_VERSION=dev
ENV APP_VERSION=${APP_VERSION}

RUN groupadd --system --gid 1001 nodejs \
 && useradd --system --uid 1001 --gid nodejs --home /app --shell /usr/sbin/nologin nextjs \
 && mkdir -p /data/files && chown -R nextjs:nodejs /data

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
# Migrations (committed SQL) and operational scripts run inside the same image: scripts/migrate.js (`migrate`
# service) and scripts/seed-catalog.js (`seed` service — generated by `pnpm build` in the builder stage from the
# TypeScript catalog, pg only). Both resolve `pg` from the standalone node_modules copied above.
COPY --from=builder --chown=nextjs:nodejs /app/drizzle ./drizzle
COPY --from=builder --chown=nextjs:nodejs /app/scripts ./scripts

USER nextjs
EXPOSE 3000
VOLUME ["/data/files"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD ["node","-e","fetch('http://127.0.0.1:3000/api/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]

CMD ["node", "server.js"]
