import * as React from "react"
import { cn } from "cn"

/* OWNED FILE (see docs/decisions.md «form controls»): generated by shadcn 4.21 radix-nova, then retuned so the
   default control is the product's 44 px target: padding + `min-h-11` (never a fixed `h-*`), `text-base leading-6`
   at every width (the generated `md:text-sm` is gone), `rounded-lg` (= `--radius`, 12 px), white `bg-surface`
   and the house `transition-base`. `controlClass` is shared with `select-native.tsx` and `textarea.tsx` so the
   three text controls are one material. If the file is ever re-generated, re-apply this block. */
const controlClass =
  "w-full min-w-0 min-h-11 rounded-lg border border-input bg-surface px-3.5 py-2 text-base leading-6 text-text transition-base outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:pointer-events-none disabled:cursor-not-allowed disabled:bg-input/50 disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:bg-input/30 dark:disabled:bg-input/80 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40"

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        controlClass,
        "file:inline-flex file:h-6 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground",
        className
      )}
      {...props}
    />
  )
}

export { Input, controlClass }
